### ISSUE TITLE
PHP timezone configuration

### ISSUE THREAD

**Issue by arnolanglade** [akeneo/Dockerfiles#167]
As it is recommended in Akeneo docs https://docs.akeneo.com/1.4/developer_guide/installation/installation_workstation.html#php we should use `Etc/UTC` instead of `Europe/Paris` to be consistent on every platform.

**Comment by jmleroux** [comment]
I think that all these [configuration modifications](https://github.com/damien-carcel/Dockerfiles/blob/master/apache-php/Dockerfile#L16) should be in a separate custom config file.
Something like `/etc/php5/mods-available/akeneo.ini` and then symlinked in `/etc/php5/apache2/conf.d/akeneo.ini` and `/etc/php5/cli/conf.d/akeneo.ini`

**Comment by damien-carcel** [comment]
@aRn0D you're right, I will change that.

@jmleroux I am not a big fan of this solution. If it is for adding new parameters, then it is the way to do it.
But here I overwrite already existing parameters. Using a new file would mean to keep the original parameter and duplicating it, new one supposed to win. I really don't like it.
Plus it is done during the build of the dockerfile, so it is internal stuff.

**Comment by jmleroux** [comment]
> Plus it is done during the build of the dockerfile, so it is internal stuff.

:+1: 

> @jmleroux I am not a big fan of this solution. If it is for adding new parameters, then it is the way to do it.
> But here I overwrite already existing parameters. Using a new file would mean to keep the original parameter and duplicating it, new one supposed to win. I really don't like it.

That's the way to do it for new or existing parameters. 

> Using a new file would mean to keep the original parameter and duplicating it, new one supposed to win

Yep, and it is totally ok for us for merging YAML parameters in our Symfony application. Why would it be so different here?
I use this convention to avoid configuration conflicts when i upgrade my packages with APT for example. This way, i always keep the package maintainer configuration and i customize it in ma personal config.
Plus, you make the modification just once. No risk to have different timezones on CLI and apache.
Last but not least, it is simpler to just copy a conf file instead of doing some tricky `sed`.

**Comment by jmleroux** [comment]
> Plus it is done during the build of the dockerfile, so it is internal stuff.

I repeat this comment, because my remark is a detail. You can of course keep going with `sed` as long as the timezone is set. :wink:

**Comment by damien-carcel** [comment]
> This way, i always keep the package maintainer configuration and i customize it in ma personal config.
Plus, you make the modification just once. No risk to have different timezones on CLI and apache.

OK, this is indeed a valid argument. I will give it some tries.
